input-training: [../data/2_F/train/front]
label-training: ../data/2_F/train/bev+occlusion
max-samples-training: 100000
input-validation: [../data/2_F/val/front]
label-validation: ../data/2_F/val/bev+occlusion
max-samples-validation: 10000

image-shape: [256, 512]
one-hot-palette-input: one_hot_conversion/convert_10.xml
one-hot-palette-label: one_hot_conversion/convert_9+occl.xml

model: architecture/uNetXST.py
unetxst-homographies: ../preprocessing/homography_converter/uNetXST_homographies/2_F.py
epochs: 80
batch-size: 16
learning-rate: 1e-4
loss-weights: [0.98684351, 2.2481491, 10.47452063, 4.78351389, 7.01028204, 8.41360361, 10.91633349, 2.38571558, 1.02473193, 2.79359197]
early-stopping-patience: 15

save-interval: 5
output-dir: output

# for training continuation, evaluation and prediction only
class-names: [road, sidewalk, person, car, truck, bus, bike, obstacle, vegetation, occluded]
# model-weights:

# for predict.py only
input-testing: [../data/2_F/val/front]
max-samples-testing: 10000
# prediction-dir:
